seed: 0
device: 0
track_in_wandb: false
save_path: "/home/adminn/theanh28/raven/w2s"
setting_DG: true # if true, train/val/test splits are done within the DG train set(finetuning and target data is different domain); if false, they are done within the OOD test set (finetune and domain target data: 1 domain)
selfMix: false

data:
  path: "/home/adminn/theanh28/DATA"
  name: "office_home"
  batch_size: 128 # for training the weak model
  n_threads: 4
  subsplit_train: [0.8, 0.2] #null # portion of the train set to train/eval on (weak model training)
  subsplit_val: [0.8, 0.2]
  subsplit_test: [0.8, 0.2]
  data_key: "id_val"
  teacher_domain: 1
  test_domain: 2

ensemble:
  ### ensemble weights optimization
  ensemble_weights_opter_cfg:
    lr: 0 # 1e-3 # lr=0 => adaptive weights turned off
  ensemble_weights_init: "uniform" # "uniform", "random", "entropy"
  ensemble_weights_per_sample: false # if true, each sample has its own set of ensemble weights
  reset_ensemble_weights_at_epoch_end_to_uniform: false
  ensemble_weights_freeze_first_frac_of_epochs:      # easy-sample guided initialization: set to the fraction of epochs where you want to train only on easy samples
  save_ensemble_weights: "all" # "none", "all", "last" (for analysis)

  ### ensemble models
  ### 
  weak_models:
  - model_name: "alexnet"
    pretrained: false
      #load_ckpt: null
    load_ckpt: "/home/adminn/theanh28/raven/w2s/office_home/models/30_seed0_pt.pt"
    freeze_backbone: false
    train: false
    train_cfg:
      domain_start_end_idxs: [0, 1]   # train/val only on a subset of domains
      domain_group: "hospital"   # train/val only on a subset of the domains of 'domain_name'
      loss_fn_name: "xent"   # "xent", "logconf", "adapt_logconf"
      loss_fn_kwargs:
      n_epochs: 40
      early_stopping_patience: 10
      load_best_model: true
      optimizer_name: "SGD"
      optimizer_kwargs:
        lr: 1e-3
        weight_decay: 1e-2
        momentum: 0.9
      scheduler_name:        # "cosine", "multiplicative"
      scheduler_mul_factor:        # only for "multiplicative" scheduler_name
  - model_name: "alexnet"
    pretrained: false
    load_ckpt: "/home/adminn/theanh28/raven/w2s/office_home/models/30_seed1_pt.pt"
    train: false
    freeze_backbone: false
  - model_name: "alexnet"
    pretrained: false
    load_ckpt: "/home/adminn/theanh28/raven/w2s/office_home/models/30_seed2_pt.pt"
    train: false
    freeze_backbone: false


w2s: # weak-to-strong (w2s) training procedure
  student_models: # add multiple models for bootstrapping
    # - model_name: "resnet50_dino"
    #   pretrained: true
    #   load_probe_ckpt: null
  - model_name: "vitb8_dino"
    pretrained: true
    load_probe_ckpt:
  add_students_to_ensemble: false

  train_val_test_split: [0.7, 0.1, 0.2] # portion of the OOD test set to train on/validate on/evaluate on
  train_val_test_split_DG: [0.8, 0.2] # portion of the DG train set to train on/validate on
  teacher_labels_loss_fn_name: "xent" # "xent", "logconf" (Conf method), "adapt_logconf" (V-sup method), "edl" (Bayes)
  teacher_labels_loss_fn_kwargs:
  gt_labels_loss_fn_name: "xent" # "xent", "logconf" (Conf method), "adapt_logconf" (V-sup method), "edl" (Bayes)
  gt_labels_loss_fn_kwargs:

  n_epochs: 30
  lr: 1e-3
  batch_size: 16

  ### easy-sample guided initialization: set to the number of epochs where you want to train only on easy samples
  ### lấy theo {10%, 20%, 50%} số epoch đầu tiên, sau đó mới train trên tất cả dữ liệu
  ignore_samples_with_disagreement_first_n_epochs:      #6 null

  ### what w2s setups to train/eval
  eval_on_id_val_data: false # for ID experiments
  id_val_data_key: "id_val" # for ID experiments
  eval_on_test_data: true # for OOD experiments
  test_data_key: "test" # for OOD experiments

  ### saving/loading
  save_labels: true
  save_embeddings: true
  load_labels: false
  load_embeddings: false

  ### Giả sử bạn lấy domain 2, 3 làm finetuning và 4 làm target (ví dụ)
  finetune_domain_idxs: [2, 4]
  target_domain_idxs: [4, 5]
  plot_w2sg: false
  plot_dim_reduction:
  - pca
  - tsne

